// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MSTestProject.AutomatedScripts
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class LoginFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Login.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Login", null, ProgrammingLanguage.CSharp, new string[] {
                        "JIRA_VISAI778",
                        "LOGIN"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Login")))
            {
                global::MSTestProject.AutomatedScripts.LoginFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
  #line 6
    testRunner.Given("I go to the VSMC site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
    testRunner.Then("I should see the VSMC login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successful system admin login and logout (uid:5b840636-7944-4afa-8175-91d2b049f56" +
            "d)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("JIRA_VISAI778")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AUTO_READY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        public virtual void SuccessfulSystemAdminLoginAndLogoutUid5B840636_7944_4Afa_8175_91D2B049F56D()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful system admin login and logout (uid:5b840636-7944-4afa-8175-91d2b049f56" +
                    "d)", null, new string[] {
                        "AUTO_READY",
                        "LOGIN"});
#line 10
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 11
    testRunner.Given("I enter a sysadmin email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
    testRunner.And("I enter a sysadmin password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
    testRunner.Then("The Log in button should be enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
    testRunner.When("I click the Log in button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
    testRunner.Then("I should see the Search Engines page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
    testRunner.And("I should see the user full name is \"System, Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
    testRunner.Then("I log out of the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
    testRunner.Then("I should see the VSMC login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
    testRunner.Then("I close all web browsers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Unsuccessful system administrator login (uid:f0d8da9d-7069-4218-ac00-ff5dd72a6eaf" +
            ")")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("JIRA_VISAI778")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AUTO_READY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        public virtual void UnsuccessfulSystemAdministratorLoginUidF0D8Da9D_7069_4218_Ac00_Ff5Dd72A6Eaf()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Unsuccessful system administrator login (uid:f0d8da9d-7069-4218-ac00-ff5dd72a6eaf" +
                    ")", null, new string[] {
                        "AUTO_READY",
                        "LOGIN"});
#line 22
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 23
    testRunner.And("I unsuccessfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successful user login and logout (uid:a682a789-3be2-4b6a-a051-e5ba383e49fa)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("JIRA_VISAI778")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AUTO_READY")]
        public virtual void SuccessfulUserLoginAndLogoutUidA682A789_3Be2_4B6A_A051_E5Ba383E49Fa()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful user login and logout (uid:a682a789-3be2-4b6a-a051-e5ba383e49fa)", null, new string[] {
                        "LOGIN",
                        "AUTO_READY"});
#line 26
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 27
    testRunner.Given("I enter a super user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
    testRunner.And("I enter a super user password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
    testRunner.Then("The Log in button should be enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
    testRunner.When("I click the Log in button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
    testRunner.And("I should see the Search Engines page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
    testRunner.When("I log out of the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
    testRunner.Then("I should see the VSMC login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Required fields for login (uid:68fbf401-d6eb-44f8-9dcd-6f3d4972e868)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("JIRA_VISAI778")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AUTO_READY")]
        public virtual void RequiredFieldsForLoginUid68Fbf401_D6Eb_44F8_9Dcd_6F3D4972E868()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Required fields for login (uid:68fbf401-d6eb-44f8-9dcd-6f3d4972e868)", null, new string[] {
                        "LOGIN",
                        "AUTO_READY"});
#line 36
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 37
    testRunner.When("I press tab on the email address field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
    testRunner.Then("I should see the Email is required message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
    testRunner.And("I should see the Password is required message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
    testRunner.And("The Log in button should be disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login attempts are not restricted (uid:78590e2a-a8e8-4cfd-9564-4112fc501f09)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("JIRA_VISAI778")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AUTO_READY")]
        public virtual void LoginAttemptsAreNotRestrictedUid78590E2A_A8E8_4Cfd_9564_4112Fc501F09()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login attempts are not restricted (uid:78590e2a-a8e8-4cfd-9564-4112fc501f09)", "    Since most systems have a login attempts limited to 3 before you are locked o" +
                    "ut or 5 in the CMS case, attempt to login five unsuccessful time and then a sixt" +
                    "h successful time.", new string[] {
                        "LOGIN",
                        "AUTO_READY"});
#line 43
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 45
    testRunner.Then("I unsuccessfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
    testRunner.Then("I unsuccessfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
    testRunner.Then("I unsuccessfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
    testRunner.Then("I unsuccessfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 49
    testRunner.Then("I unsuccessfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
    testRunner.Then("I successfully login as a SYSADMIN", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Restrictions on email and password fields (uid:d40bf40f-8c25-4225-9fba-f173232b7e" +
            "01)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("JIRA_VISAI778")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LOGIN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AUTO_READY")]
        public virtual void RestrictionsOnEmailAndPasswordFieldsUidD40Bf40F_8C25_4225_9Fba_F173232B7E01()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restrictions on email and password fields (uid:d40bf40f-8c25-4225-9fba-f173232b7e" +
                    "01)", null, new string[] {
                        "LOGIN",
                        "AUTO_READY"});
#line 53
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 54
    testRunner.Given("I enter a bad email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
    testRunner.Then("I should see the message \"Email must be a valid email address\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
    testRunner.When("I clear the email address field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
    testRunner.And("I enter a sysadmin email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
    testRunner.And("I enter a short password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
    testRunner.Then("I should see the message \"Password must be at least 8 characters\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
    testRunner.And("The Log in button should be disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
